<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="65412" started-at="2017-06-14T03:34:50Z" finished-at="2017-06-14T03:35:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="65412" started-at="2017-06-14T03:34:50Z" finished-at="2017-06-14T03:35:56Z">
      <class name="tournament.pract_1">
        <test-method status="PASS" signature="testPlanEnter()[pri:0, instance:tournament.pract_1@12405818]" name="testPlanEnter" is-config="true" duration-ms="7" started-at="2017-06-14T09:04:50Z" finished-at="2017-06-14T09:04:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPlanEnter -->
        <test-method status="PASS" signature="testCaseEnter(java.lang.reflect.Method)[pri:0, instance:tournament.pract_1@12405818]" name="testCaseEnter" is-config="true" duration-ms="64150" started-at="2017-06-14T09:04:50Z" finished-at="2017-06-14T09:05:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tournament.pract_1.tt3() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseEnter -->
        <test-method status="FAIL" signature="tt3()[pri:0, instance:tournament.pract_1@12405818]" name="tt3" duration-ms="125" started-at="2017-06-14T09:05:54Z" finished-at="2017-06-14T09:05:54Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field dugout.WelcomePage.xpath_btnWelcomeSignIn to com.sun.proxy.$Proxy9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field dugout.WelcomePage.xpath_btnWelcomeSignIn to com.sun.proxy.$Proxy9
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:92)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:79)
	at dugout.WelcomePage.<init>(WelcomePage.java:16)
	at dugout.SignInPage.signIn(SignInPage.java:46)
	at tournament.pract_1.tt3(pract_1.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tt3 -->
        <test-method status="PASS" signature="testCaseExit(org.testng.ITestResult, java.lang.reflect.Method)[pri:0, instance:tournament.pract_1@12405818]" name="testCaseExit" is-config="true" duration-ms="1127" started-at="2017-06-14T09:05:54Z" finished-at="2017-06-14T09:05:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=tt3 status=FAILURE method=pract_1.tt3()[pri:0, instance:tournament.pract_1@12405818] output={null}]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void tournament.pract_1.tt3() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseExit -->
      </class> <!-- tournament.pract_1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
